// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShelterApi.Models;

#nullable disable

namespace ShelterApi.Migrations
{
    [DbContext(typeof(ShelterApiContext))]
    [Migration("20230331171138_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Breed = "Scottish Fold",
                            Name = "Salmon",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 12,
                            Breed = "King Charles Cavalier",
                            Name = "Andre",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            Breed = "Dalmatian",
                            Name = "Sid",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 4,
                            Breed = "Ragdoll",
                            Name = "Blade",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 2,
                            Breed = "Rotweiller",
                            Name = "Baby",
                            Species = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
